# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=4
PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="*-jython 3.*"

inherit distutils eutils

MY_PN="zookeeper"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="ZooKeeper python bindings"
HOMEPAGE="http://pypi.python.org/pypi/zkpython"
SRC_URI="mirror://apache/${MY_PN}/${MY_P}/${MY_P}.tar.gz"
LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="=sys-cluster/apache-zookeeper-c-${PV}"

S="${WORKDIR}/${MY_P}/src/contrib/zkpython/src/c"

src_prepare() {
	epatch -p6 "$FILESDIR/zookeeper-3.3.4-0002-make-sure-the-client-password-isn-t-corrupted.patch"
	cat <<EOF >setup.py
from setuptools import setup, Extension
extension = Extension( name='zookeeper', sources=['zookeeper.c'],
                       include_dirs=['/usr/include/zookeeper'],
                       libraries=['zookeeper_mt'],
                       extra_compile_args=['-Wall', '-Wextra', '-Wno-unused-parameter'],
                       )
setup( name='zookeeper', version='${PV}', ext_modules=[extension])
EOF
	default_src_prepare
}
