# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=3
PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"

inherit distutils

DESCRIPTION="A human-readable alternative to dir"
HOMEPAGE="http://inky.github.com/see/"
SRC_URI="http://pypi.python.org/packages/source/s/see/${P}.zip"
LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="app-arch/unzip"
